version: '3'
services:
    test-app-php:
        container_name: test-app-php
        build: ./docker/php
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./:/var/www
        depends_on:
            - test-app-mysql
    test-app-nginx:
        container_name: test-app-nginx
        image: nginx
        ports:
            - 8888:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - test-app-php
    test-app-mysql:
        container_name: test-app-mysql
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "13306:3306"
        environment:
            MYSQL_DATABASE: test-app
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        volumes:
            - ./docker/mysql_data:/var/lib/mysql
            - ./docker/mysql_initdb.d:/docker-entrypoint-initdb.d
